# Generated by Django 6.0.8 on 2026-09-13 11:00

from django.db import migrations, models


def create_trgm_index(apps, schema_editor):
    """Enable pg_trgm + trigram GIN index for fast ILIKE search on 60k+ rows."""
    if schema_editor.connection.vendor != 'postgresql':
        return  # no-op under sqlite
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
        cursor.execute('CREATE INDEX IF NOT EXISTS store_product_name_trgm '
                       'ON store_product USING gin (name gin_trgm_ops)')


def drop_trgm_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP INDEX IF EXISTS store_product_name_trgm')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('cheapshark', 'CheapShark'), ('search_import', 'Search-time import'), ('steamspy', 'SteamSpy')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='Store page for this deal'),
        ),
        migrations.AddField(
            model_name='product',
            name='metacritic_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='steam_app_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Steam appid — used as import/upsert key', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='steam_enriched',
            field=models.BooleanField(default=False, help_text='Genres/description fetched from Steam'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Hotlinked image (e.g. Steam CDN capsule art)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Local file (downloaded). Optional when external_url is set.', upload_to='products/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='store_produ_is_acti_19c4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['data_source'], name='store_produ_data_so_911d0d_idx'),
        ),
        migrations.RunPython(create_trgm_index, drop_trgm_index, elidable=True),
    ]
