# Generated by Django 6.0.8 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_data_source_product_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('nay_bank', 'Nay Bank Transfer'), ('bank_transfer', 'Bank Transfer (legacy)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
