# Generated by Django 6.0.8 on 2026-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Hotlinked image (e.g. Steam CDN capsule art)', max_length=500),
        ),
    ]
