# Generated by Django 6.0.8 on 2026-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Generated card thumbnail (WebP). Materialized from external_url by 'materialize_images'.", upload_to='artwork/thumbs/'),
        ),
    ]
