# Generated by Django 6.0.8 on 2026-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='art_unavailable',
            field=models.BooleanField(default=False, help_text='Set when every artwork source (Steam CDN + appdetails) confirms no image exists (delisted app). The fetch pipeline then stops retrying this row, so boots stay fast and quiet.'),
        ),
    ]
