# Generated by Django 6.0.8 on 2026-09-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_go_digital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='Nepal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saved Billing Detail',
                'verbose_name_plural': 'Saved Billing Details',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(3, 'AAA'), (2, 'AA'), (1, 'Indie'), (0, 'Free')], db_index=True, default=1, help_text='Production tier — drives homepage prominence and default ordering'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('nay_bank', 'Nay Bank Transfer'), ('bank_transfer', 'Bank Transfer (legacy)')], default='esewa', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'tier'], name='store_produ_is_acti_7fc179_idx'),
        ),
        migrations.AddField(
            model_name='savedbillingdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_billing', to=settings.AUTH_USER_MODEL),
        ),
    ]
