# Generated by Django 6.0.8 on 2026-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_savedbillingdetail_product_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owners',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='Estimated owner count (SteamSpy midpoint) — real popularity signal behind AAA/AA ranking. Set by the rank_catalog command.'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('game', 'Game'), ('application', 'Application')], db_index=True, default='game', help_text='Whether this listing is a game or a non-game application (software/utility). Set by the classify_catalog command.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'product_type'], name='store_produ_is_acti_2e3679_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'owners'], name='store_produ_product_e1141a_idx'),
        ),
    ]
