# Generated by Django 6.0.8 on 2026-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_owners_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='NewaStore', max_length=100),
        ),
    ]
