from decimal import Decimal
import json

from django.test import TestCase, Client
from django.contrib.auth.models import User
from django.core import mail
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta

from .models import (
    Category, Tag, Product, ProductImage, ProductVariant, Review, Coupon,
    Address, Cart, CartItem, Wishlist, Order, OrderItem, OrderStatusHistory,
    ShippingMethod, NewsletterSubscriber, SiteSettings, ContactMessage,
)
from .cart import CartManager
from .utils import mark_order_paid


def make_product(**kwargs):
    defaults = dict(
        name='Test Game', price=Decimal('1000'), discount_price=Decimal('800'),
        description='A test product', stock_quantity=10, is_active=True,
    )
    defaults.update(kwargs)
    return Product.objects.create(**defaults)


class ProductModelTests(TestCase):
    def test_current_price_uses_discount(self):
        p = make_product()
        self.assertEqual(p.current_price, Decimal('800'))

    def test_discount_percentage(self):
        p = make_product(price=Decimal('1000'), discount_price=Decimal('750'))
        self.assertEqual(p.discount_percentage, 25)

    def test_in_stock(self):
        p = make_product(stock_quantity=5)
        self.assertTrue(p.is_in_stock)
        p.stock_quantity = 0
        p.save()
        self.assertFalse(p.is_in_stock)

    def test_backorder_allows_stock(self):
        p = make_product(stock_quantity=0, allow_backorder=True)
        self.assertTrue(p.is_in_stock)

    def test_slug_autogenerated(self):
        p = make_product(name='Unique Product Name')
        self.assertEqual(p.slug, 'unique-product-name')

    def test_average_rating(self):
        p = make_product()
        u1 = User.objects.create_user('u1', password='x')
        u2 = User.objects.create_user('u2', password='x')
        u3 = User.objects.create_user('u3', password='x')
        Review.objects.create(product=p, user=u1, rating=5, comment='Great', is_approved=True)
        Review.objects.create(product=p, user=u2, rating=3, comment='Ok', is_approved=True)
        Review.objects.create(product=p, user=u3, rating=1, comment='Hidden', is_approved=False)
        self.assertEqual(p.average_rating, 4.0)
        self.assertEqual(p.review_count, 2)


class CategoryTests(TestCase):
    def test_slug(self):
        c = Category.objects.create(name='Video Games')
        self.assertEqual(c.slug, 'video-games')

    def test_absolute_url(self):
        c = Category.objects.create(name='Consoles')
        self.assertEqual(c.get_absolute_url(), '/category/consoles/')


class CouponTests(TestCase):
    def setUp(self):
        now = timezone.now()
        self.coupon = Coupon.objects.create(
            code='SAVE10', name='Save 10', discount_type='percentage',
            discount_value=Decimal('10'), minimum_amount=Decimal('100'),
            valid_from=now - timedelta(days=1), valid_until=now + timedelta(days=1),
            is_active=True, usage_limit_per_user=1,
        )

    def test_valid_coupon(self):
        valid, _ = self.coupon.is_valid(None, Decimal('500'))
        self.assertTrue(valid)

    def test_below_minimum(self):
        valid, msg = self.coupon.is_valid(None, Decimal('50'))
        self.assertFalse(valid)

    def test_percentage_discount(self):
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('100'))

    def test_fixed_discount(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('150')
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('150'))

    def test_fixed_discount_capped(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('500')
        self.assertEqual(self.coupon.calculate_discount(Decimal('200')), Decimal('200'))


class CartManagerTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.client = Client()

    def test_add_to_cart_guest(self):
        response = self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        self.assertEqual(response.status_code, 302)
        cart = Cart.objects.first()
        self.assertIsNotNone(cart)
        self.assertEqual(cart.items_count, 2)

    def test_add_same_product_accumulates(self):
        url = reverse('add_to_cart', args=[self.product.id])
        self.client.post(url, {'quantity': 1})
        self.client.post(url, {'quantity': 1})
        self.assertEqual(Cart.objects.first().items_count, 2)

    def test_cart_totals(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 3})
        cart = Cart.objects.first()
        self.assertEqual(cart.subtotal, Decimal('2400'))

    def test_update_quantity(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        item = CartItem.objects.first()
        self.client.post(reverse('update_cart', args=[item.id]), {'quantity': 5})
        item.refresh_from_db()
        self.assertEqual(item.quantity, 5)


class ViewTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Games')
        self.product = make_product(category=self.category, is_featured=True)
        self.user = User.objects.create_user('tester', password='pass12345',
                                              email='t@example.com')

    def test_home(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Newa')

    def test_product_list(self):
        response = self.client.get(reverse('product_list'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_product_detail(self):
        response = self.client.get(reverse('product_detail', args=[self.product.slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_category_detail(self):
        response = self.client.get(reverse('category_detail', args=[self.category.slug]))
        self.assertEqual(response.status_code, 200)

    def test_search(self):
        response = self.client.get(reverse('search'), {'q': 'Test'})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_search_no_results(self):
        response = self.client.get(reverse('search'), {'q': 'zzzzzznotfound'})
        self.assertEqual(response.status_code, 200)

    def test_cart_page_guest(self):
        response = self.client.get(reverse('cart'))
        self.assertEqual(response.status_code, 200)

    def test_static_pages(self):
        for name in ['about', 'contact', 'faq', 'privacy', 'terms', 'shipping_returns']:
            response = self.client.get(reverse(name))
            self.assertEqual(response.status_code, 200, name)

    def test_register(self):
        response = self.client.post(reverse('register'), {
            'username': 'newuser', 'first_name': 'New', 'last_name': 'User',
            'email': 'new@example.com', 'password1': 'complexpass123',
            'password2': 'complexpass123',
        })
        self.assertEqual(response.status_code, 302)
        self.assertTrue(User.objects.filter(username='newuser').exists())

    def test_newsletter_subscribe(self):
        response = self.client.post(reverse('newsletter_subscribe'), {'email': 'n@example.com'})
        self.assertEqual(response.status_code, 302)
        self.assertTrue(NewsletterSubscriber.objects.filter(email='n@example.com').exists())


class CheckoutTests(TestCase):
    def setUp(self):
        SiteSettings.get_settings()
        ShippingMethod.objects.create(
            name='Standard', price=Decimal('100'), estimated_days_min=3,
            estimated_days_max=5, is_active=True)
        self.product = make_product(stock_quantity=10)
        self.user = User.objects.create_user('buyer', password='pass12345',
                                              email='buyer@example.com')

    def _checkout_payload(self):
        return {
            'billing_full_name': 'Buyer One', 'billing_phone': '9800000000',
            'billing_email': 'buyer@example.com', 'billing_address_line_1': 'Main St',
            'billing_address_line_2': '', 'billing_city': 'Kathmandu',
            'billing_state': 'Bagmati', 'billing_postal_code': '44600',
            'billing_country': 'Nepal',
            'shipping_option': 'same',
            'shipping_method': ShippingMethod.objects.first().id,
            'payment_method': 'cod',
            'order_notes': '',
            'terms_accepted': 'on',
        }

    def test_cod_checkout_creates_order(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertEqual(order.items.count(), 1)
        self.assertEqual(order.status, 'confirmed')
        self.assertEqual(order.payment_method, 'cod')
        # cart should be cleared
        self.assertEqual(Cart.objects.first().items_count, 0)
        # stock reduced
        self.product.refresh_from_db()
        self.assertEqual(self.product.stock_quantity, 8)

    def test_digital_checkout_uses_free_digital_delivery(self):
        """Digital-only carts skip paid shipping and use the free Digital Delivery method."""
        product = make_product(
            name='Digital Key', is_digital=True, requires_shipping=False,
            stock_quantity=0, track_inventory=False,
        )
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.filter(items__product_name='Digital Key').first()
        self.assertIsNotNone(order)
        self.assertEqual(order.shipping_method, 'Digital Delivery')
        self.assertEqual(order.shipping_cost, Decimal('0'))

    def test_guest_checkout(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertIsNone(order.user)
        self.assertEqual(order.guest_email, 'buyer@example.com')

    def test_order_totals_include_tax_and_shipping(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        self.client.post(reverse('checkout'), self._checkout_payload())
        order = Order.objects.first()
        # product price 800 (discounted) + 100 shipping, tax 13% on 800
        self.assertEqual(order.subtotal, Decimal('800'))
        self.assertEqual(order.shipping_cost, Decimal('100'))
        self.assertEqual(order.tax_amount, Decimal('104.00'))
        self.assertEqual(order.total, Decimal('1004.00'))


class WishlistTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('wisher', password='pass12345')
        self.client.login(username='wisher', password='pass12345')

    def test_toggle_add(self):
        response = self.client.post(reverse('wishlist_toggle', args=[self.product.id]))
        self.assertEqual(response.status_code, 302)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 1)

    def test_toggle_remove(self):
        url = reverse('wishlist_toggle', args=[self.product.id])
        self.client.post(url)
        self.client.post(url)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 0)


class ReviewTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('reviewer', password='pass12345')
        self.client.login(username='reviewer', password='pass12345')

    def test_add_review(self):
        response = self.client.post(reverse('add_review', args=[self.product.slug]), {
            'rating': 5, 'title': 'Awesome', 'comment': 'Loved it!',
        })
        self.assertEqual(response.status_code, 302)
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)

    def test_duplicate_review_blocked(self):
        url = reverse('add_review', args=[self.product.slug])
        self.client.post(url, {'rating': 5, 'title': 'A', 'comment': 'Great'})
        self.client.post(url, {'rating': 4, 'title': 'B', 'comment': 'Again'})
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)


class OrderModelTests(TestCase):
    def test_order_number_generated(self):
        order = Order.objects.create(subtotal=Decimal('100'), total=Decimal('100'))
        self.assertTrue(order.order_number.startswith('ORD-'))

    def test_customer_name_guest(self):
        order = Order.objects.create(
            subtotal=Decimal('100'), total=Decimal('100'),
            billing_address={'full_name': 'Guest Person'})
        self.assertEqual(order.customer_name, 'Guest Person')


class AuthFlowTests(TestCase):
    """Register / login (email-or-username) / logout / password reset."""

    def test_register_creates_user_authenticates_and_welcomes(self):
        response = self.client.post(reverse('register'), {
            'username': 'newgamer',
            'first_name': 'New',
            'last_name': 'Gamer',
            'email': 'newgamer@example.com',
            'phone': '',
            'password1': 'StrongPass!123',
            'password2': 'StrongPass!123',
        })
        self.assertEqual(response.status_code, 302)
        user = User.objects.get(username='newgamer')
        self.assertTrue(user.is_authenticated)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn('Welcome to Newa Store', mail.outbox[0].subject)

    def test_login_by_username_and_by_email(self):
        User.objects.create_user('gamer1', email='gamer1@example.com', password='Secret123!')
        self.assertTrue(self.client.login(username='gamer1', password='Secret123!'))
        self.client.logout()
        self.assertTrue(self.client.login(username='gamer1@example.com', password='Secret123!'))

    def test_logout_requires_post(self):
        User.objects.create_user('logoutuser', password='Secret123!')
        self.client.login(username='logoutuser', password='Secret123!')
        self.assertEqual(self.client.get(reverse('logout')).status_code, 405)
        self.assertEqual(self.client.post(reverse('logout')).status_code, 302)

    def test_password_reset_sends_email(self):
        User.objects.create_user('resetme', email='resetme@example.com', password='Secret123!')
        response = self.client.post(reverse('password_reset'), {'email': 'resetme@example.com'})
        self.assertEqual(response.status_code, 302)
        self.assertEqual(len(mail.outbox), 1)


class PaymentFulfillmentTests(TestCase):
    """Stripe / PayPal checkout + webhook fulfillment via mark_order_paid."""

    def _make_order(self, **kw):
        defaults = dict(
            subtotal=Decimal('1000'),
            total=Decimal('1130'),
            tax_amount=Decimal('130'),
            guest_email='buyer@example.com',
            payment_method='stripe',
        )
        defaults.update(kw)
        return Order.objects.create(**defaults)

    def test_mark_order_paid_is_idempotent(self):
        order = self._make_order()
        mark_order_paid(order, gateway='stripe', txn_id='pi_test_1')
        mark_order_paid(order, gateway='stripe', txn_id='pi_test_1')
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.status, 'confirmed')
        self.assertIsNotNone(order.confirmed_at)
        self.assertEqual(order.payment_transaction_id, 'pi_test_1')
        # single status-history record; status + receipt emails sent once
        self.assertEqual(OrderStatusHistory.objects.filter(order=order).count(), 1)
        self.assertEqual(len(mail.outbox), 2)

    def test_stripe_webhook_fulfills_order(self):
        order = self._make_order()
        payload = json.dumps({
            'type': 'payment_intent.succeeded',
            'data': {'object': {'id': 'pi_wh_1', 'metadata': {'order_number': order.order_number}}},
        })
        response = self.client.post(reverse('stripe_webhook'), payload, content_type='application/json')
        self.assertEqual(response.status_code, 200)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.payment_transaction_id, 'pi_wh_1')

    def test_stripe_webhook_rejects_bad_payload(self):
        response = self.client.post(reverse('stripe_webhook'), 'not-json', content_type='application/json')
        self.assertEqual(response.status_code, 400)

    def test_paypal_webhook_fulfills_order(self):
        order = self._make_order(payment_method='paypal')
        payload = json.dumps({
            'event_type': 'PAYMENT.CAPTURE.COMPLETED',
            'resource': {
                'id': 'CAP-123',
                'supplementary_data': {'related_ids': {'order_id': order.order_number}},
            },
        })
        response = self.client.post(reverse('paypal_webhook'), payload, content_type='application/json')
        self.assertEqual(response.status_code, 200)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.payment_transaction_id, 'CAP-123')

    def test_stripe_intent_requires_post_and_501_when_unconfigured(self):
        order = self._make_order()
        url = reverse('stripe_create_intent', args=[order.order_number])
        self.assertEqual(self.client.get(url).status_code, 405)
        response = self.client.post(url)
        self.assertEqual(response.status_code, 501)
        self.assertFalse(response.json()['success'])

    def test_stripe_checkout_redirects_when_unconfigured(self):
        order = self._make_order()
        response = self.client.get(reverse('stripe_checkout', args=[order.order_number]))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse('payment_failed', args=[order.order_number]), response.url)

    def test_paypal_create_order_501_when_unconfigured(self):
        order = self._make_order(payment_method='paypal')
        response = self.client.post(reverse('paypal_create_order', args=[order.order_number]))
        self.assertEqual(response.status_code, 501)
        self.assertFalse(response.json()['success'])

    def test_paypal_capture_requires_token(self):
        order = self._make_order(payment_method='paypal')
        response = self.client.get(reverse('paypal_capture', args=[order.order_number]))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse('payment_failed', args=[order.order_number]), response.url)


class ApiTests(TestCase):
    """Public JSON API endpoints (/api/...)."""

    def setUp(self):
        self.product = make_product(name='Cyber Runner 2077')
        self.tag = Tag.objects.create(name='Action')
        self.product.tags.add(self.tag)

    def test_health_returns_ok(self):
        response = self.client.get(reverse('api_health'))
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['status'], 'ok')
        self.assertTrue(data['database'])

    def test_search_by_query(self):
        response = self.client.get(reverse('api_search'), {'q': 'Cyber'})
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['count'], 1)
        self.assertEqual(data['results'][0]['name'], 'Cyber Runner 2077')

    def test_browse_filters_and_paginates(self):
        response = self.client.get(reverse('api_browse'), {'on_sale_only': '1', 'sort_by': 'price'})
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['count'], 1)
        result = data['results'][0]
        self.assertIn('current_price', result)
        self.assertIn('discount_percentage', result)

    def test_game_detail(self):
        response = self.client.get(reverse('api_game_detail', args=[self.product.slug]))
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['name'], 'Cyber Runner 2077')
        self.assertEqual(data['genres'], ['Action'])

    def test_genres_with_counts(self):
        response = self.client.get(reverse('api_genres'))
        self.assertEqual(response.status_code, 200)
        genres = response.json()
        self.assertTrue(genres)
        self.assertEqual(genres[0]['slug'], 'action')
        self.assertGreaterEqual(genres[0]['product_count'], 1)

    def test_contact_creates_message_and_emails(self):
        response = self.client.post(reverse('api_contact'), {
            'name': 'API Fan',
            'email': 'fan@example.com',
            'subject': 'Question',
            'message': 'Is this store open?',
        })
        self.assertEqual(response.status_code, 201)
        self.assertTrue(ContactMessage.objects.filter(email='fan@example.com').exists())
        self.assertEqual(len(mail.outbox), 1)

    def test_contact_rejects_invalid(self):
        response = self.client.post(reverse('api_contact'), {'email': 'not-an-email'})
        self.assertEqual(response.status_code, 400)
        self.assertFalse(response.json()['success'])
