from decimal import Decimal

from django.test import TestCase, Client
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta

from .models import (
    Category, Tag, Product, ProductImage, ProductVariant, Review, Coupon,
    Address, Cart, CartItem, Wishlist, Order, OrderItem, ShippingMethod,
    NewsletterSubscriber, SiteSettings,
)
from .cart import CartManager


def make_product(**kwargs):
    defaults = dict(
        name='Test Game', price=Decimal('1000'), discount_price=Decimal('800'),
        description='A test product', stock_quantity=10, is_active=True,
    )
    defaults.update(kwargs)
    return Product.objects.create(**defaults)


class ProductModelTests(TestCase):
    def test_current_price_uses_discount(self):
        p = make_product()
        self.assertEqual(p.current_price, Decimal('800'))

    def test_discount_percentage(self):
        p = make_product(price=Decimal('1000'), discount_price=Decimal('750'))
        self.assertEqual(p.discount_percentage, 25)

    def test_in_stock(self):
        p = make_product(stock_quantity=5)
        self.assertTrue(p.is_in_stock)
        p.stock_quantity = 0
        p.save()
        self.assertFalse(p.is_in_stock)

    def test_backorder_allows_stock(self):
        p = make_product(stock_quantity=0, allow_backorder=True)
        self.assertTrue(p.is_in_stock)

    def test_slug_autogenerated(self):
        p = make_product(name='Unique Product Name')
        self.assertEqual(p.slug, 'unique-product-name')

    def test_average_rating(self):
        p = make_product()
        u1 = User.objects.create_user('u1', password='x')
        u2 = User.objects.create_user('u2', password='x')
        u3 = User.objects.create_user('u3', password='x')
        Review.objects.create(product=p, user=u1, rating=5, comment='Great', is_approved=True)
        Review.objects.create(product=p, user=u2, rating=3, comment='Ok', is_approved=True)
        Review.objects.create(product=p, user=u3, rating=1, comment='Hidden', is_approved=False)
        self.assertEqual(p.average_rating, 4.0)
        self.assertEqual(p.review_count, 2)


class CategoryTests(TestCase):
    def test_slug(self):
        c = Category.objects.create(name='Video Games')
        self.assertEqual(c.slug, 'video-games')

    def test_absolute_url(self):
        c = Category.objects.create(name='Consoles')
        self.assertEqual(c.get_absolute_url(), '/category/consoles/')


class CouponTests(TestCase):
    def setUp(self):
        now = timezone.now()
        self.coupon = Coupon.objects.create(
            code='SAVE10', name='Save 10', discount_type='percentage',
            discount_value=Decimal('10'), minimum_amount=Decimal('100'),
            valid_from=now - timedelta(days=1), valid_until=now + timedelta(days=1),
            is_active=True, usage_limit_per_user=1,
        )

    def test_valid_coupon(self):
        valid, _ = self.coupon.is_valid(None, Decimal('500'))
        self.assertTrue(valid)

    def test_below_minimum(self):
        valid, msg = self.coupon.is_valid(None, Decimal('50'))
        self.assertFalse(valid)

    def test_percentage_discount(self):
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('100'))

    def test_fixed_discount(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('150')
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('150'))

    def test_fixed_discount_capped(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('500')
        self.assertEqual(self.coupon.calculate_discount(Decimal('200')), Decimal('200'))


class CartManagerTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.client = Client()

    def test_add_to_cart_guest(self):
        response = self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        self.assertEqual(response.status_code, 302)
        cart = Cart.objects.first()
        self.assertIsNotNone(cart)
        self.assertEqual(cart.items_count, 2)

    def test_add_same_product_accumulates(self):
        url = reverse('add_to_cart', args=[self.product.id])
        self.client.post(url, {'quantity': 1})
        self.client.post(url, {'quantity': 1})
        self.assertEqual(Cart.objects.first().items_count, 2)

    def test_cart_totals(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 3})
        cart = Cart.objects.first()
        self.assertEqual(cart.subtotal, Decimal('2400'))

    def test_update_quantity(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        item = CartItem.objects.first()
        self.client.post(reverse('update_cart', args=[item.id]), {'quantity': 5})
        item.refresh_from_db()
        self.assertEqual(item.quantity, 5)


class ViewTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Games')
        self.product = make_product(category=self.category, is_featured=True)
        self.user = User.objects.create_user('tester', password='pass12345',
                                              email='t@example.com')

    def test_home(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Newa')

    def test_product_list(self):
        response = self.client.get(reverse('product_list'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_product_detail(self):
        response = self.client.get(reverse('product_detail', args=[self.product.slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_category_detail(self):
        response = self.client.get(reverse('category_detail', args=[self.category.slug]))
        self.assertEqual(response.status_code, 200)

    def test_search(self):
        response = self.client.get(reverse('search'), {'q': 'Test'})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_search_no_results(self):
        response = self.client.get(reverse('search'), {'q': 'zzzzzznotfound'})
        self.assertEqual(response.status_code, 200)

    def test_cart_page_guest(self):
        response = self.client.get(reverse('cart'))
        self.assertEqual(response.status_code, 200)

    def test_static_pages(self):
        for name in ['about', 'contact', 'faq', 'privacy', 'terms', 'shipping_returns']:
            response = self.client.get(reverse(name))
            self.assertEqual(response.status_code, 200, name)

    def test_register(self):
        response = self.client.post(reverse('register'), {
            'username': 'newuser', 'first_name': 'New', 'last_name': 'User',
            'email': 'new@example.com', 'password1': 'complexpass123',
            'password2': 'complexpass123',
        })
        self.assertEqual(response.status_code, 302)
        self.assertTrue(User.objects.filter(username='newuser').exists())

    def test_newsletter_subscribe(self):
        response = self.client.post(reverse('newsletter_subscribe'), {'email': 'n@example.com'})
        self.assertEqual(response.status_code, 302)
        self.assertTrue(NewsletterSubscriber.objects.filter(email='n@example.com').exists())


class CheckoutTests(TestCase):
    def setUp(self):
        SiteSettings.get_settings()
        ShippingMethod.objects.create(
            name='Standard', price=Decimal('100'), estimated_days_min=3,
            estimated_days_max=5, is_active=True)
        self.product = make_product(stock_quantity=10)
        self.user = User.objects.create_user('buyer', password='pass12345',
                                              email='buyer@example.com')

    def _checkout_payload(self):
        return {
            'billing_full_name': 'Buyer One', 'billing_phone': '9800000000',
            'billing_email': 'buyer@example.com', 'billing_address_line_1': 'Main St',
            'billing_address_line_2': '', 'billing_city': 'Kathmandu',
            'billing_state': 'Bagmati', 'billing_postal_code': '44600',
            'billing_country': 'Nepal',
            'shipping_option': 'same',
            'shipping_method': ShippingMethod.objects.first().id,
            'payment_method': 'cod',
            'order_notes': '',
            'terms_accepted': 'on',
        }

    def test_cod_checkout_creates_order(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertEqual(order.items.count(), 1)
        self.assertEqual(order.status, 'confirmed')
        self.assertEqual(order.payment_method, 'cod')
        # cart should be cleared
        self.assertEqual(Cart.objects.first().items_count, 0)
        # stock reduced
        self.product.refresh_from_db()
        self.assertEqual(self.product.stock_quantity, 8)

    def test_digital_checkout_uses_free_digital_delivery(self):
        """Digital-only carts skip paid shipping and use the free Digital Delivery method."""
        product = make_product(
            name='Digital Key', is_digital=True, requires_shipping=False,
            stock_quantity=0, track_inventory=False,
        )
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.filter(items__product_name='Digital Key').first()
        self.assertIsNotNone(order)
        self.assertEqual(order.shipping_method, 'Digital Delivery')
        self.assertEqual(order.shipping_cost, Decimal('0'))

    def test_guest_checkout(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertIsNone(order.user)
        self.assertEqual(order.guest_email, 'buyer@example.com')

    def test_order_totals_include_tax_and_shipping(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        self.client.post(reverse('checkout'), self._checkout_payload())
        order = Order.objects.first()
        # product price 800 (discounted) + 100 shipping, tax 13% on 800
        self.assertEqual(order.subtotal, Decimal('800'))
        self.assertEqual(order.shipping_cost, Decimal('100'))
        self.assertEqual(order.tax_amount, Decimal('104.00'))
        self.assertEqual(order.total, Decimal('1004.00'))


class WishlistTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('wisher', password='pass12345')
        self.client.login(username='wisher', password='pass12345')

    def test_toggle_add(self):
        response = self.client.post(reverse('wishlist_toggle', args=[self.product.id]))
        self.assertEqual(response.status_code, 302)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 1)

    def test_toggle_remove(self):
        url = reverse('wishlist_toggle', args=[self.product.id])
        self.client.post(url)
        self.client.post(url)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 0)


class ReviewTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('reviewer', password='pass12345')
        self.client.login(username='reviewer', password='pass12345')

    def test_add_review(self):
        response = self.client.post(reverse('add_review', args=[self.product.slug]), {
            'rating': 5, 'title': 'Awesome', 'comment': 'Loved it!',
        })
        self.assertEqual(response.status_code, 302)
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)

    def test_duplicate_review_blocked(self):
        url = reverse('add_review', args=[self.product.slug])
        self.client.post(url, {'rating': 5, 'title': 'A', 'comment': 'Great'})
        self.client.post(url, {'rating': 4, 'title': 'B', 'comment': 'Again'})
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)


class OrderModelTests(TestCase):
    def test_order_number_generated(self):
        order = Order.objects.create(subtotal=Decimal('100'), total=Decimal('100'))
        self.assertTrue(order.order_number.startswith('ORD-'))

    def test_customer_name_guest(self):
        order = Order.objects.create(
            subtotal=Decimal('100'), total=Decimal('100'),
            billing_address={'full_name': 'Guest Person'})
        self.assertEqual(order.customer_name, 'Guest Person')
