from decimal import Decimal
import io
import json
from io import StringIO

from django.test import TestCase, Client
from django.contrib.auth.models import User
from django.core import mail
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta

from .models import (
    Category, Tag, Product, ProductImage, ProductVariant, Review, Coupon,
    Cart, CartItem, Wishlist, Order, OrderItem, OrderStatusHistory,
    NewsletterSubscriber, SiteSettings, ContactMessage,
)
from .cart import CartManager
from .utils import mark_order_paid


def make_product(**kwargs):
    defaults = dict(
        name='Test Game', price=Decimal('1000'), discount_price=Decimal('800'),
        description='A test product', stock_quantity=10, is_active=True,
    )
    defaults.update(kwargs)
    return Product.objects.create(**defaults)


class ProductModelTests(TestCase):
    def test_current_price_uses_discount(self):
        p = make_product()
        self.assertEqual(p.current_price, Decimal('800'))

    def test_discount_percentage(self):
        p = make_product(price=Decimal('1000'), discount_price=Decimal('750'))
        self.assertEqual(p.discount_percentage, 25)

    def test_in_stock(self):
        p = make_product(stock_quantity=5)
        self.assertTrue(p.is_in_stock)
        p.stock_quantity = 0
        p.save()
        self.assertFalse(p.is_in_stock)

    def test_backorder_allows_stock(self):
        p = make_product(stock_quantity=0, allow_backorder=True)
        self.assertTrue(p.is_in_stock)

    def test_slug_autogenerated(self):
        p = make_product(name='Unique Product Name')
        self.assertEqual(p.slug, 'unique-product-name')

    def test_average_rating(self):
        p = make_product()
        u1 = User.objects.create_user('u1', password='x')
        u2 = User.objects.create_user('u2', password='x')
        u3 = User.objects.create_user('u3', password='x')
        Review.objects.create(product=p, user=u1, rating=5, comment='Great', is_approved=True)
        Review.objects.create(product=p, user=u2, rating=3, comment='Ok', is_approved=True)
        Review.objects.create(product=p, user=u3, rating=1, comment='Hidden', is_approved=False)
        self.assertEqual(p.average_rating, 4.0)
        self.assertEqual(p.review_count, 2)


class CategoryTests(TestCase):
    def test_slug(self):
        c = Category.objects.create(name='Video Games')
        self.assertEqual(c.slug, 'video-games')

    def test_absolute_url(self):
        c = Category.objects.create(name='Consoles')
        self.assertEqual(c.get_absolute_url(), '/category/consoles/')


class CouponTests(TestCase):
    def setUp(self):
        now = timezone.now()
        self.coupon = Coupon.objects.create(
            code='SAVE10', name='Save 10', discount_type='percentage',
            discount_value=Decimal('10'), minimum_amount=Decimal('100'),
            valid_from=now - timedelta(days=1), valid_until=now + timedelta(days=1),
            is_active=True, usage_limit_per_user=1,
        )

    def test_valid_coupon(self):
        valid, _ = self.coupon.is_valid(None, Decimal('500'))
        self.assertTrue(valid)

    def test_below_minimum(self):
        valid, msg = self.coupon.is_valid(None, Decimal('50'))
        self.assertFalse(valid)

    def test_percentage_discount(self):
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('100'))

    def test_fixed_discount(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('150')
        self.assertEqual(self.coupon.calculate_discount(Decimal('1000')), Decimal('150'))

    def test_fixed_discount_capped(self):
        self.coupon.discount_type = 'fixed'
        self.coupon.discount_value = Decimal('500')
        self.assertEqual(self.coupon.calculate_discount(Decimal('200')), Decimal('200'))


class CartManagerTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.client = Client()

    def test_add_to_cart_guest(self):
        response = self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        self.assertEqual(response.status_code, 302)
        cart = Cart.objects.first()
        self.assertIsNotNone(cart)
        self.assertEqual(cart.items_count, 2)

    def test_add_same_product_accumulates(self):
        url = reverse('add_to_cart', args=[self.product.id])
        self.client.post(url, {'quantity': 1})
        self.client.post(url, {'quantity': 1})
        self.assertEqual(Cart.objects.first().items_count, 2)

    def test_cart_totals(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 3})
        cart = Cart.objects.first()
        self.assertEqual(cart.subtotal, Decimal('2400'))

    def test_update_quantity(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        item = CartItem.objects.first()
        self.client.post(reverse('update_cart', args=[item.id]), {'quantity': 5})
        item.refresh_from_db()
        self.assertEqual(item.quantity, 5)


class ViewTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Games')
        self.product = make_product(category=self.category, is_featured=True)
        self.user = User.objects.create_user('tester', password='pass12345',
                                              email='t@example.com')

    def test_home(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Newa')

    def test_product_list(self):
        response = self.client.get(reverse('product_list'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_product_detail(self):
        response = self.client.get(reverse('product_detail', args=[self.product.slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_category_detail(self):
        response = self.client.get(reverse('category_detail', args=[self.category.slug]))
        self.assertEqual(response.status_code, 200)

    def test_search(self):
        response = self.client.get(reverse('search'), {'q': 'Test'})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.name)

    def test_search_no_results(self):
        response = self.client.get(reverse('search'), {'q': 'zzzzzznotfound'})
        self.assertEqual(response.status_code, 200)

    def test_cart_page_guest(self):
        response = self.client.get(reverse('cart'))
        self.assertEqual(response.status_code, 200)

    def test_static_pages(self):
        for name in ['about', 'contact', 'faq', 'privacy', 'terms', 'refund_policy']:
            response = self.client.get(reverse(name))
            self.assertEqual(response.status_code, 200, name)

    def test_register(self):
        response = self.client.post(reverse('register'), {
            'username': 'newuser', 'first_name': 'New', 'last_name': 'User',
            'email': 'new@example.com', 'password1': 'complexpass123',
            'password2': 'complexpass123',
        })
        self.assertEqual(response.status_code, 302)
        self.assertTrue(User.objects.filter(username='newuser').exists())

    def test_newsletter_subscribe(self):
        response = self.client.post(reverse('newsletter_subscribe'), {'email': 'n@example.com'})
        self.assertEqual(response.status_code, 302)
        self.assertTrue(NewsletterSubscriber.objects.filter(email='n@example.com').exists())


class CheckoutTests(TestCase):
    def setUp(self):
        SiteSettings.get_settings()
        self.product = make_product(stock_quantity=10)
        self.user = User.objects.create_user('buyer', password='pass12345',
                                              email='buyer@example.com')

    def _checkout_payload(self):
        return {
            'billing_full_name': 'Buyer One', 'billing_phone': '9800000000',
            'billing_email': 'buyer@example.com', 'billing_address_line_1': 'Main St',
            'billing_address_line_2': '', 'billing_city': 'Kathmandu',
            'billing_state': 'Bagmati', 'billing_postal_code': '44600',
            'billing_country': 'Nepal',
            'payment_method': 'nay_bank',
            'order_notes': '',
            'terms_accepted': 'on',
        }

    def test_nay_bank_checkout_creates_order(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 2})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertEqual(order.items.count(), 1)
        self.assertEqual(order.status, 'pending')
        self.assertEqual(order.payment_method, 'nay_bank')
        self.assertEqual(Cart.objects.first().items_count, 0)
        self.product.refresh_from_db()
        self.assertEqual(self.product.stock_quantity, 8)

    def test_digital_checkout_has_no_shipping_cost(self):
        """Digital keys have no delivery fee: order total is subtotal + tax only."""
        product = make_product(
            name='Digital Key', is_digital=True,
            stock_quantity=0, track_inventory=False,
        )
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.filter(items__product_name='Digital Key').first()
        self.assertIsNotNone(order)
        self.assertEqual(order.total, order.subtotal + order.tax_amount)

    def test_guest_checkout(self):
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        response = self.client.post(reverse('checkout'), self._checkout_payload())
        self.assertEqual(response.status_code, 302)
        order = Order.objects.first()
        self.assertIsNotNone(order)
        self.assertIsNone(order.user)
        self.assertEqual(order.guest_email, 'buyer@example.com')

    def test_order_totals_include_tax_no_shipping(self):
        self.client.login(username='buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        self.client.post(reverse('checkout'), self._checkout_payload())
        order = Order.objects.first()
        # product price 800 (discounted), tax 13% on 800, no shipping
        self.assertEqual(order.subtotal, Decimal('800'))
        self.assertEqual(order.tax_amount, Decimal('104.00'))
        self.assertEqual(order.total, Decimal('904.00'))


class WishlistTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('wisher', password='pass12345')
        self.client.login(username='wisher', password='pass12345')

    def test_toggle_add(self):
        response = self.client.post(reverse('wishlist_toggle', args=[self.product.id]))
        self.assertEqual(response.status_code, 302)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 1)

    def test_toggle_remove(self):
        url = reverse('wishlist_toggle', args=[self.product.id])
        self.client.post(url)
        self.client.post(url)
        wl = Wishlist.objects.get(user=self.user)
        self.assertEqual(wl.items.count(), 0)


class ReviewTests(TestCase):
    def setUp(self):
        self.product = make_product()
        self.user = User.objects.create_user('reviewer', password='pass12345')
        self.client.login(username='reviewer', password='pass12345')

    def test_add_review(self):
        response = self.client.post(reverse('add_review', args=[self.product.slug]), {
            'rating': 5, 'title': 'Awesome', 'comment': 'Loved it!',
        })
        self.assertEqual(response.status_code, 302)
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)

    def test_duplicate_review_blocked(self):
        url = reverse('add_review', args=[self.product.slug])
        self.client.post(url, {'rating': 5, 'title': 'A', 'comment': 'Great'})
        self.client.post(url, {'rating': 4, 'title': 'B', 'comment': 'Again'})
        self.assertEqual(Review.objects.filter(product=self.product).count(), 1)


class OrderModelTests(TestCase):
    def test_order_number_generated(self):
        order = Order.objects.create(subtotal=Decimal('100'), total=Decimal('100'))
        self.assertTrue(order.order_number.startswith('ORD-'))

    def test_customer_name_guest(self):
        order = Order.objects.create(
            subtotal=Decimal('100'), total=Decimal('100'),
            billing_address={'full_name': 'Guest Person'})
        self.assertEqual(order.customer_name, 'Guest Person')


class AuthFlowTests(TestCase):
    """Register / login (email-or-username) / logout / password reset."""

    def test_register_creates_user_authenticates_and_welcomes(self):
        response = self.client.post(reverse('register'), {
            'username': 'newgamer',
            'first_name': 'New',
            'last_name': 'Gamer',
            'email': 'newgamer@example.com',
            'phone': '',
            'password1': 'StrongPass!123',
            'password2': 'StrongPass!123',
        })
        self.assertEqual(response.status_code, 302)
        user = User.objects.get(username='newgamer')
        self.assertTrue(user.is_authenticated)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn('Welcome to Newa Store', mail.outbox[0].subject)

    def test_login_by_username_and_by_email(self):
        User.objects.create_user('gamer1', email='gamer1@example.com', password='Secret123!')
        self.assertTrue(self.client.login(username='gamer1', password='Secret123!'))
        self.client.logout()
        self.assertTrue(self.client.login(username='gamer1@example.com', password='Secret123!'))

    def test_logout_requires_post(self):
        User.objects.create_user('logoutuser', password='Secret123!')
        self.client.login(username='logoutuser', password='Secret123!')
        self.assertEqual(self.client.get(reverse('logout')).status_code, 405)
        self.assertEqual(self.client.post(reverse('logout')).status_code, 302)

    def test_password_reset_sends_email(self):
        User.objects.create_user('resetme', email='resetme@example.com', password='Secret123!')
        response = self.client.post(reverse('password_reset'), {'email': 'resetme@example.com'})
        self.assertEqual(response.status_code, 302)
        self.assertEqual(len(mail.outbox), 1)


class PaymentFulfillmentTests(TestCase):
    """Stripe / PayPal checkout + webhook fulfillment via mark_order_paid."""

    def _make_order(self, **kw):
        defaults = dict(
            subtotal=Decimal('1000'),
            total=Decimal('1130'),
            tax_amount=Decimal('130'),
            guest_email='buyer@example.com',
            payment_method='stripe',
        )
        defaults.update(kw)
        return Order.objects.create(**defaults)

    def test_mark_order_paid_is_idempotent(self):
        order = self._make_order()
        mark_order_paid(order, gateway='stripe', txn_id='pi_test_1')
        mark_order_paid(order, gateway='stripe', txn_id='pi_test_1')
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.status, 'confirmed')
        self.assertIsNotNone(order.confirmed_at)
        self.assertEqual(order.payment_transaction_id, 'pi_test_1')
        # single status-history record; status + receipt emails sent once
        self.assertEqual(OrderStatusHistory.objects.filter(order=order).count(), 1)
        self.assertEqual(len(mail.outbox), 2)

    def test_stripe_webhook_fulfills_order(self):
        order = self._make_order()
        payload = json.dumps({
            'type': 'payment_intent.succeeded',
            'data': {'object': {'id': 'pi_wh_1', 'metadata': {'order_number': order.order_number}}},
        })
        response = self.client.post(reverse('stripe_webhook'), payload, content_type='application/json')
        self.assertEqual(response.status_code, 200)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.payment_transaction_id, 'pi_wh_1')

    def test_stripe_webhook_rejects_bad_payload(self):
        response = self.client.post(reverse('stripe_webhook'), 'not-json', content_type='application/json')
        self.assertEqual(response.status_code, 400)

    def test_paypal_webhook_fulfills_order(self):
        order = self._make_order(payment_method='paypal')
        payload = json.dumps({
            'event_type': 'PAYMENT.CAPTURE.COMPLETED',
            'resource': {
                'id': 'CAP-123',
                'supplementary_data': {'related_ids': {'order_id': order.order_number}},
            },
        })
        response = self.client.post(reverse('paypal_webhook'), payload, content_type='application/json')
        self.assertEqual(response.status_code, 200)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.payment_transaction_id, 'CAP-123')

    def test_stripe_intent_requires_post_and_501_when_unconfigured(self):
        order = self._make_order()
        url = reverse('stripe_create_intent', args=[order.order_number])
        self.assertEqual(self.client.get(url).status_code, 405)
        response = self.client.post(url)
        self.assertEqual(response.status_code, 501)
        self.assertFalse(response.json()['success'])

    def test_stripe_checkout_redirects_when_unconfigured(self):
        order = self._make_order()
        response = self.client.get(reverse('stripe_checkout', args=[order.order_number]))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse('payment_failed', args=[order.order_number]), response.url)

    def test_paypal_create_order_501_when_unconfigured(self):
        order = self._make_order(payment_method='paypal')
        response = self.client.post(reverse('paypal_create_order', args=[order.order_number]))
        self.assertEqual(response.status_code, 501)
        self.assertFalse(response.json()['success'])

    def test_paypal_capture_requires_token(self):
        order = self._make_order(payment_method='paypal')
        response = self.client.get(reverse('paypal_capture', args=[order.order_number]))
        self.assertEqual(response.status_code, 302)
        self.assertIn(reverse('payment_failed', args=[order.order_number]), response.url)

    def test_checkout_hides_unconfigured_gateways(self):
        """No Stripe/PayPal radios render when their keys are missing (.env)."""
        user = User.objects.create_user('buyer2', password='pass12345')
        self.client.login(username='buyer2', password='pass12345')
        product = make_product(stock_quantity=10)
        self.client.post(reverse('add_to_cart', args=[product.id]), {'quantity': 1})
        response = self.client.get(reverse('checkout'))
        self.assertEqual(response.status_code, 200)
        html = response.content.decode()
        self.assertNotIn('value="stripe"', html)
        self.assertNotIn('value="paypal"', html)
        self.assertIn('value="esewa"', html)

    def test_checkout_rejects_unconfigured_gateway_on_post(self):
        """POSTing payment_method=stripe without keys fails validation (no order)."""
        user = User.objects.create_user('buyer3', password='pass12345')
        self.client.login(username='buyer3', password='pass12345')
        product = make_product(stock_quantity=10)
        self.client.post(reverse('add_to_cart', args=[product.id]), {'quantity': 1})
        payload = {
            'billing_full_name': 'Buyer Three', 'billing_phone': '9800000000',
            'billing_email': 'buyer3@example.com', 'billing_address_line_1': 'Main St',
            'billing_address_line_2': '', 'billing_city': 'Kathmandu',
            'billing_state': 'Bagmati', 'billing_postal_code': '44600',
            'billing_country': 'Nepal',
            'payment_method': 'stripe',
            'order_notes': '', 'terms_accepted': 'on',
        }
        response = self.client.post(reverse('checkout'), payload)
        self.assertNotEqual(response.status_code, 302)
        self.assertEqual(Order.objects.count(), 0)


class BootstrapTests(TestCase):
    """ensure_ready must be safe, incremental and network-free when idle."""

    def test_ensure_ready_with_all_steps_skipped_completes(self):
        from django.core.management import call_command
        from django.conf import settings
        from pathlib import Path

        state_file = Path(settings.BASE_DIR) / ".bootstrap_state.json"
        if state_file.exists():
            state_file.unlink()

        out = StringIO()
        # Everything skipped: no migrations, no import, no repair, no audit.
        call_command("ensure_ready", skip_migrate=True, skip_import=True,
                     skip_repair=True, skip_audit=True, stdout=out)
        text = out.getvalue()
        self.assertIn("Bootstrap finished", text)
        self.assertNotIn("Repairing artwork", text)
        self.assertNotIn("importing the full SteamSpy catalog", text)

    def test_ensure_ready_skips_repair_when_cadence_blocks_it(self):
        """A recent attempt with an unchanged placeholder count is not retried."""
        import json as jsonlib
        from django.core.management import call_command
        from django.conf import settings
        from django.utils import timezone
        from pathlib import Path

        state_file = Path(settings.BASE_DIR) / ".bootstrap_state.json"
        state = {
            "audit_after_id": 0,
            "audit_completed_at": timezone.now().isoformat(),
            "repair_last_at": timezone.now().isoformat(),
            "repair_last_count": 0,
            "import_last_at": timezone.now().isoformat(),
        }
        state_file.write_text(jsonlib.dumps(state), encoding="utf-8")
        try:
            out = StringIO()
            call_command("ensure_ready", skip_migrate=True, skip_import=True,
                         skip_audit=True, stdout=out)
            self.assertIn("Artwork repair: nothing to do", out.getvalue())
        finally:
            if state_file.exists():
                state_file.unlink()

    def test_ensure_ready_ignores_corrupt_state_file(self):
        from django.core.management import call_command
        from django.conf import settings
        from pathlib import Path

        state_file = Path(settings.BASE_DIR) / ".bootstrap_state.json"
        state_file.write_text("{not valid json", encoding="utf-8")
        try:
            out = StringIO()
            call_command("ensure_ready", skip_migrate=True, skip_import=True,
                         skip_repair=True, skip_audit=True, stdout=out)
            self.assertIn("Bootstrap finished", out.getvalue())
        finally:
            if state_file.exists():
                state_file.unlink()

    def test_runserver_command_exposes_bootstrap_flags(self):
        from django.core.management import get_commands, load_command_class
        app = get_commands()["runserver"]
        self.assertEqual(app, "store")  # our override wins over staticfiles
        cmd = load_command_class(app, "runserver")
        from store.management.commands.runserver import Command as RSCommand
        self.assertIsInstance(cmd, RSCommand)
        import argparse
        parser = argparse.ArgumentParser()
        cmd.add_arguments(parser)
        flags = {a.option_strings[0] for a in parser._actions if a.option_strings}
        self.assertIn("--skip-bootstrap", flags)
        self.assertIn("--force-bootstrap", flags)
        self.assertIn("--bootstrap-workers", flags)
        # and it still supports the vanilla flags
        self.assertIn("--noreload", flags)
        self.assertIn("--nostatic", flags)


class ApiTests(TestCase):
    """Public JSON API endpoints (/api/...)."""

    def setUp(self):
        self.product = make_product(name='Cyber Runner 2077')
        self.tag = Tag.objects.create(name='Action')
        self.product.tags.add(self.tag)

    def test_health_returns_ok(self):
        response = self.client.get(reverse('api_health'))
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['status'], 'ok')
        self.assertTrue(data['database'])

    def test_search_by_query(self):
        response = self.client.get(reverse('api_search'), {'q': 'Cyber'})
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['count'], 1)
        self.assertEqual(data['results'][0]['name'], 'Cyber Runner 2077')

    def test_browse_filters_and_paginates(self):
        response = self.client.get(reverse('api_browse'), {'on_sale_only': '1', 'sort_by': 'price'})
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['count'], 1)
        result = data['results'][0]
        self.assertIn('current_price', result)
        self.assertIn('discount_percentage', result)

    def test_game_detail(self):
        response = self.client.get(reverse('api_game_detail', args=[self.product.slug]))
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data['name'], 'Cyber Runner 2077')
        self.assertEqual(data['genres'], ['Action'])

    def test_genres_with_counts(self):
        response = self.client.get(reverse('api_genres'))
        self.assertEqual(response.status_code, 200)
        genres = response.json()
        self.assertTrue(genres)
        self.assertEqual(genres[0]['slug'], 'action')
        self.assertGreaterEqual(genres[0]['product_count'], 1)

    def test_contact_creates_message_and_emails(self):
        response = self.client.post(reverse('api_contact'), {
            'name': 'API Fan',
            'email': 'fan@example.com',
            'subject': 'Question',
            'message': 'Is this store open?',
        })
        self.assertEqual(response.status_code, 201)
        self.assertTrue(ContactMessage.objects.filter(email='fan@example.com').exists())
        self.assertEqual(len(mail.outbox), 1)

    def test_contact_rejects_invalid(self):
        response = self.client.post(reverse('api_contact'), {'email': 'not-an-email'})
        self.assertEqual(response.status_code, 400)
        self.assertFalse(response.json()['success'])
class SimulatedGatewayTests(TestCase):
    """eSewa/Khalti are demo wallets (local simulation); Nay Bank is offline.

    Nothing may contact an external provider: checkout has to render a local
    page, and only the local "simulate" endpoint may flip an order to paid.
    """

    def setUp(self):
        SiteSettings.get_settings()
        self.product = make_product(stock_quantity=10)
        self.user = User.objects.create_user(
            'sim_buyer', password='pass12345', email='sim@example.com')

    def _start_checkout(self, payment_method):
        """Add a product, then place the order paying with `payment_method`."""
        self.client.login(username='sim_buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        payload = {
            'billing_full_name': 'Sim Buyer', 'billing_phone': '9800000000',
            'billing_email': 'sim@example.com', 'billing_address_line_1': 'Main St',
            'billing_address_line_2': '', 'billing_city': 'Kathmandu',
            'billing_state': 'Bagmati', 'billing_postal_code': '44600',
            'billing_country': 'Nepal',
            'payment_method': payment_method,
            'order_notes': '', 'terms_accepted': 'on',
        }
        return self.client.post(reverse('checkout'), payload)

    # ---------------------------------------------------------- checkout UI

    def test_checkout_offers_simulated_wallets_and_nay_bank(self):
        self.client.login(username='sim_buyer', password='pass12345')
        self.client.post(reverse('add_to_cart', args=[self.product.id]), {'quantity': 1})
        html = self.client.get(reverse('checkout')).content.decode()
        self.assertIn('value="esewa"', html)
        self.assertIn('value="khalti"', html)
        self.assertIn('value="nay_bank"', html)
        self.assertIn('eSewa (Simulated)', html)
        self.assertIn('Khalti (Simulated)', html)
        self.assertIn('Nay Bank Transfer', html)

# ------------------------------------------------- eSewa / Khalti (demo)

    def test_esewa_checkout_renders_local_page_instead_of_redirect(self):
        response = self._start_checkout('esewa')
        self.assertEqual(response.status_code, 200)
        html = response.content.decode()
        self.assertIn('Simulated payment', html)
        self.assertIn('eSewa', html)
        # no external gateway may be contacted
        self.assertNotIn('esewa.com.np', html)
        order = Order.objects.get()
        self.assertEqual(order.payment_method, 'esewa')
        self.assertEqual(order.payment_status, 'pending')
        self.assertFalse(order.is_paid)

    def test_khalti_checkout_renders_local_page_instead_of_redirect(self):
        response = self._start_checkout('khalti')
        self.assertEqual(response.status_code, 200)
        html = response.content.decode()
        self.assertIn('Simulated payment', html)
        self.assertIn('Khalti', html)
        self.assertNotIn('khalti.com', html)
        order = Order.objects.get()
        self.assertEqual(order.payment_method, 'khalti')
        self.assertFalse(order.is_paid)

    def test_simulated_success_marks_order_paid(self):
        self._start_checkout('esewa')
        order = Order.objects.get()
        response = self.client.post(
            reverse('simulate_payment', args=[order.order_number, 'esewa']),
            {'outcome': 'success'})
        self.assertRedirects(
            response, reverse('order_success', args=[order.order_number]),
            fetch_redirect_response=False)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')
        self.assertEqual(order.status, 'confirmed')
        self.assertTrue(order.is_paid)
        self.assertTrue(order.payment_transaction_id.startswith('SIM-'))
        self.assertIsNotNone(order.confirmed_at)

    def test_simulated_failure_marks_order_failed(self):
        self._start_checkout('khalti')
        order = Order.objects.get()
        response = self.client.post(
            reverse('simulate_payment', args=[order.order_number, 'khalti']),
            {'outcome': 'failure'})
        self.assertRedirects(
            response, reverse('payment_failed', args=[order.order_number]),
            fetch_redirect_response=False)
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'failed')
        self.assertFalse(order.is_paid)

    def test_simulation_is_idempotent_on_already_paid_order(self):
        """A late 'declined' click must not un-pay a settled order."""
        self._start_checkout('esewa')
        order = Order.objects.get()
        url = reverse('simulate_payment', args=[order.order_number, 'esewa'])
        self.client.post(url, {'outcome': 'success'})
        self.client.post(url, {'outcome': 'failure'})
        order.refresh_from_db()
        self.assertEqual(order.payment_status, 'paid')

    def test_simulate_payment_404s_for_unknown_gateway(self):
        order = Order.objects.create(subtotal=Decimal('100'), total=Decimal('100'))
        response = self.client.get(
            reverse('simulate_payment', args=[order.order_number, 'stripe']))
        self.assertEqual(response.status_code, 404)

    def test_simulated_gateway_page_references_no_external_hosts(self):
        """Belt and braces: the demo page must not point at any gateway host."""
        self._start_checkout('esewa')
        order = Order.objects.get()
        html = self.client.get(
            reverse('simulate_payment', args=[order.order_number, 'esewa'])).content.decode()
        for host in ('esewa.com.np', 'khalti.com', 'js.stripe.com', 'paypal.com'):
            self.assertNotIn(host, html)

    # ------------------------------------------------------ Nay Bank transfer

    def test_nay_bank_order_stays_pending_and_shows_account_details(self):
        response = self._start_checkout('nay_bank')
        order = Order.objects.get()
        self.assertRedirects(
            response, reverse('order_success', args=[order.order_number]),
            fetch_redirect_response=False)
        self.assertEqual(order.payment_method, 'nay_bank')
        self.assertEqual(order.payment_status, 'pending')
        self.assertEqual(order.status, 'pending')

        page = self.client.get(reverse('order_success', args=[order.order_number]))
        html = page.content.decode()
        self.assertIn('Nay Bank', html)
        self.assertIn('Complete your bank transfer', html)
        self.assertIn('0123456789012', html)  # demo account number
        self.assertIn(order.order_number, html)

    def test_nay_bank_details_only_render_for_bank_orders(self):
        """A non-bank (eSewa) order must not display bank transfer instructions."""
        self._start_checkout('esewa')
        order = Order.objects.get()
        html = self.client.get(
            reverse('order_success', args=[order.order_number])).content.decode()
        self.assertNotIn('Complete your bank transfer', html)
        self.assertNotIn('0123456789012', html)
